name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  gitops_branch_name: cluster-lab-13

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CONTAINER_REG_1 }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
      - name: Update GitOps repository
        shell: bash
        env:
          GIT_TOKEN: ${{ secrets.GITOPS_REPO_1 }}
        run: |
          # Configure git credential store
          git config --global credential.helper store
          echo "https://${GIT_TOKEN}:x-oauth-basic@github.com" > ~/.git-credentials
          
          echo "credentiaaaals"
          cat ~/.git-credentials
          
          # Remove any existing gitops directory
          rm -rf gitops
          
          # Clone repository using HTTPS URL without token
          git clone https://github.com/hamletrp/k8s-tests.git gitops
          cd ./gitops
          git checkout $gitops_branch_name
          cd ./app-charts-enduser/charts/gradeapp

          yq e '.image.tag = "${{ github.sha }}"' -i values.yaml
          cat ./values.yaml
          
          # Commit changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add values.yaml
          git commit -m "Update image to ${{ github.sha }}"
          
          # Push
          git push -f https://${GIT_TOKEN}@github.com/hamletrp/k8s-tests.git $gitops_branch_name
